config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5], message: 'is not between 0-5' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="navbar bg-light d-flex">
  <h2>Finder</h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= simple_form_for (@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
        <%= f.input :phone_number %>
        <%= f.submit "Edit Restaurant", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="navbar bg-light d-flex">
  <h2>Finder</h2>
  <%= link_to "Add a new restaurant", new_restaurant_path, class: 'btn btn-primary' %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-1">
      <% @restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant) do %>
          <h1 class="text-success"><%= restaurant.name %></h1>
        <% end %>
        <p><%= restaurant.category %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="navbar bg-light d-flex">
  <h2>Finder</h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
        <%= f.input :phone_number %>
        <%= f.submit "Add Restaurant", class: "btn btn-primary" %>
        <%= link_to "Back to list", restaurants_path, class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="navbar bg-light d-flex">
  <h2>Finder</h2>
  <%= link_to "Add a new review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-1">
      <h1 class="text-success"><%= @restaurant.name %></h1>
       <h3><%= @restaurant.address %></h3>
        <p><%= @restaurant.phone_number %></p>
        <p class="text-danger"><%= @restaurant.category %></p>
        <p>
        <strong>Reviews:</strong>
        <% @restaurant.reviews.each do |review| %>
          <li><%= link_to review.content, review_path(review) %>
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
        <% end %>
        </li>
      </p>
      <%= link_to "Back to list", restaurants_path, class: "btn btn-primary" %>
      <%= link_to "Edit", edit_restaurant_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Back to list", restaurant_path(@restaurant), class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-1">
      <h1>Review for <%= @review.restaurant.name %>:</h1>
      <p><%= @review.content %></p>
      <p>
        <% @review.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - @review.rating).times do %>
          <i class="far fa-star"></i>
        <% end %>
      </p>
    </div>
  </div>
</div>